# Generated by Django 4.0 on 2022-01-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='PrixT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produits',
            name='PrixU',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produits',
            name='Quantitee',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produit', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=30)),
                ('Quantitee', models.IntegerField(default=0)),
                ('PrixU', models.IntegerField(default=0)),
                ('PrixT', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Id_Produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.produits')),
            ],
        ),
    ]
