# Generated by Django 4.0 on 2022-01-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_alter_produits_prixt_alter_produits_prixu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='Id_Produit',
        ),
    ]
