# Generated by Django 4.0 on 2022-01-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_remove_vente_id_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
