# Generated by Django 4.0 on 2022-01-13 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0004_alter_vente_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='Produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.produits'),
        ),
    ]
