# Generated by Django 4.0 on 2022-01-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0005_alter_vente_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='produits',
            name='Produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.libelle'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.marque'),
        ),
    ]
