# Generated by Django 4.0 on 2022-01-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0006_libelle_marque_alter_produits_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='Produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.libelle'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.marque'),
        ),
    ]
