# Generated by Django 4.0 on 2022-01-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0007_alter_vente_produit_alter_vente_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='Produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.produits'),
        ),
    ]
