# Generated by Django 4.0 on 2022-01-17 22:55

import Stock.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0008_alter_vente_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='Type',
            field=models.CharField(max_length=30, verbose_name=Stock.models.Produits),
        ),
    ]
