# Generated by Django 4.0 on 2022-01-17 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0009_alter_vente_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.marque'),
        ),
    ]
